# image: https://hub.docker.com/r/bitnami/suitecrm
# docs: https://github.com/bitnami/bitnami-docker-suitecrm

 
version: '3.8'

services:
  guacd:
    image: dushixiang/guacd:latest
    volumes:
      - guacd:/usr/local/next-terminal/data
    restart:
          always
          
  next-terminal:
    image: dushixiang/next-terminal:latest
    environment:
      DB: sqlite
      GUACD_HOSTNAME: guacd
      GUACD_PORT: 4822
    ports:
      - "${APP_HTTP_PORT}:8088"
    volumes:
      - /etc/localtime:/etc/localtime
      - next_terminal:/usr/local/next-terminal/data
    restart:
      always
      
networks:
  default:
    name: ${APP_NETWORK}
    external: true

volumes:
  guacd:
  next_terminal:
